import sql from './lib/db';
async function run() {
  try {
    const res = await sql`SELECT content_json FROM pages WHERE slug = 'ac-blowing-warm-air' LIMIT 1`;
    if (!res || res.length === 0) {
      console.log('No page found');
      process.exit(0);
    }
    const content = res[0].content_json;
    console.log('--- KEYS GENERATED BY AI ---');
    console.log(Object.keys(content));
    
    console.log('\n--- VALUES ---');
    console.log('repair_paths:', content.repair_paths);
    console.log('comparison:', content.comparison);
    console.log('prevention:', content.prevention);
    console.log('tools:', content.tools);
    
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
run();
