/**
 * Symptom Layout Config — Section Order by Layout
 * ----------------------------------------------
 * layout → section keys in display order.
 * @see docs/MASTER-PROMPT-CANARY.md
 */

export const SYMPTOM_LAYOUTS: Record<string, string[]> = {
  diagnostic_first: [
    "hero",
    "system_overview",
    "technician_summary",
    "fast_answer",
    "conditional_diagram",
    "most_common_fix",
    "diagnostic_flow",
    "guided_filters",
    "causes",
    "repairs",
    "repair_matrix",
    "tools",
    "components",
    "costs",
    "insights",
    "warnings",
    "mistakes",
    "environmental_factors",
    "prevention",
    "cta",
    "faq",
    "internal_links",
  ],
  repair_first: [
    "hero",
    "system_overview",
    "fast_answer",
    "conditional_diagram",
    "most_common_fix",
    "repairs",
    "repair_matrix",
    "causes",
    "diagnostic_flow",
    "guided_filters",
    "tools",
    "components",
    "costs",
    "insights",
    "warnings",
    "mistakes",
    "environmental_factors",
    "prevention",
    "cta",
    "faq",
    "internal_links",
  ],
  cost_first: [
    "hero",
    "system_overview",
    "fast_answer",
    "conditional_diagram",
    "costs",
    "most_common_fix",
    "repairs",
    "repair_matrix",
    "causes",
    "diagnostic_flow",
    "guided_filters",
    "tools",
    "components",
    "insights",
    "warnings",
    "mistakes",
    "environmental_factors",
    "prevention",
    "cta",
    "faq",
    "internal_links",
  ],
  scenario_first: [
    "hero",
    "system_overview",
    "guided_filters",
    "conditional_diagram",
    "fast_answer",
    "causes",
    "most_common_fix",
    "repairs",
    "diagnostic_flow",
    "repair_matrix",
    "tools",
    "components",
    "costs",
    "insights",
    "warnings",
    "mistakes",
    "environmental_factors",
    "prevention",
    "cta",
    "faq",
    "internal_links",
  ],
};
