export {
  HSD_CTA_TYPES,
  injectProgrammaticHsdCtas,
  normalizeCtasOnJson,
} from "@/lib/hsd/injectProgrammaticHsdCtas";
export {
  HSD_V25_BLOCK_PRIORITY,
  joinSortedHsdV25Blocks,
  renderHsdV25,
  renderHsdV25Closing,
  renderHsdV25HeaderOnly,
  renderHsdV25LeadSegments,
  renderHsdV25MidThroughDecision,
  sectionInternalRelatedLinks,
  sectionPlacementCta,
  sectionSummary,
  sectionWhatThisMeans,
  sectionQuickChecks,
  sectionDiagnosticSteps,
  sectionCanonicalTruths,
  sectionDecisionTreeText,
  sectionQuickTable,
  sectionQuickDiagnosisTable,
  sectionTools,
  renderMermaid,
  sectionRepairMatrix,
  sectionCostEscalation,
  sectionDecision,
  sectionCta,
  sectionFinal,
  sectionFinalWarning,
  wrapHsdV25LayoutDocument,
  type HsdV25HtmlBlock,
  type HsdV25RenderInput,
} from "@/src/lib/hsd/renderHsdV25";
