export type PageType =
  | "system"
  | "symptom"
  | "diagnostic"
  | "cause"
  | "repair"
  | "component"
  | "condition"
  | "authority"
  | "city";

export type ValidationResult = {
  valid: boolean;
  score: number;
  retryable: boolean;
  reasons: string[];
  hardReject: boolean;
  sectionScores: {
    schema: number;
    intent: number;
    depth: number;
    eeat: number;
    readability: number;
    actionability: number;
    originality: number;
  };
};

export const HARDCODED_DEFAULT_PATTERNS: RegExp[] = [
  /common issue that can have several causes/i,
  /it is important to inspect the system carefully/i,
  /consult a professional if the problem persists/i,
  /this issue may affect performance and comfort/i,
  /several factors may contribute to this problem/i,
  /a number of issues can cause this symptom/i,
];

export const PUBLISH_THRESHOLDS: Record<PageType, number> = {
  system: 85,
  symptom: 85,
  diagnostic: 90,
  cause: 85,
  repair: 85,
  component: 83,
  condition: 83,
  authority: 88,
  city: 80,
};

function getContent(page: any) {
  // Handle double-nested content wrapper generated by Phase 2 pipeline
  if (page?.content?.content) {
    return page.content.content;
  }
  return page?.content ?? page ?? {};
}

function flattenText(input: any): string {
  if (input == null) return "";
  if (typeof input === "string") return input;
  if (Array.isArray(input)) return input.map(flattenText).join(" ");
  if (typeof input === "object") return Object.values(input).map(flattenText).join(" ");
  return String(input);
}

function wordCount(page: any): number {
  const text = flattenText(page);
  return text.trim() ? text.trim().split(/\s+/).length : 0;
}

function countPatternMatches(text: string, patterns: RegExp[]): number {
  return patterns.reduce((acc, re) => acc + (re.test(text) ? 1 : 0), 0);
}

function hasExpertObservation(content: any): boolean {
  const t = flattenText(content.tech_observation ?? "");
  if (t.length >= 120) return true;

  const all = flattenText(content);
  return (
    /what most homeowners misunderstand/i.test(all) ||
    /what people often miss/i.test(all) ||
    /failure pattern/i.test(all) ||
    /hidden cause/i.test(all) ||
    /cascading/i.test(all)
  );
}

export function scoreSchema(page: any, pageType: PageType, reasons: string[]): number {
  const c = getContent(page);
  let score = 20;

  if (!page?.slug) {
    score -= 5;
    reasons.push("Missing slug.");
  }
  if (!page?.title) {
    score -= 5;
    reasons.push("Missing title.");
  }

  if (pageType === "diagnostic") {
    if (!c.decision_tree) {
      score -= 5;
      reasons.push("Missing decision_tree.");
    }
    if (!Array.isArray(c.system_explanation) || c.system_explanation.length < 4) {
      score -= 4;
      reasons.push("system_explanation is missing or too short.");
    }
    if (!Array.isArray(c.diagnostic_flow) || c.diagnostic_flow.length < 3) {
      score -= 3;
      reasons.push("diagnostic_flow is missing or too short.");
    }
    if (!Array.isArray(c.top_causes) || c.top_causes.length < 3) {
      score -= 2;
      reasons.push("top_causes is missing or too short.");
    }
    if (!Array.isArray(c.repair_matrix) || c.repair_matrix.length < 3) {
      score -= 2;
      reasons.push("repair_matrix is missing or too short.");
    }
    if (!Array.isArray(c.quick_tools) || c.quick_tools.length < 3) {
      score -= 1;
      reasons.push("quick_tools is missing or too short.");
    }
  }

  return Math.max(0, score);
}

export function scoreIntent(page: any, pageType: PageType, reasons: string[]): number {
  const c = getContent(page);
  const text = flattenText(c).toLowerCase();
  let score = 15;

  const requiredSignals: Record<PageType, string[]> = {
    system: ["component", "how it works", "failure"],
    symptom: ["symptom", "cause", "check"],
    diagnostic: ["diagnostic", "cause", "step"],
    cause: ["why it happens", "confirm", "fix"],
    repair: ["repair", "cost", "difficulty"],
    component: ["component", "function", "failure"],
    condition: ["condition", "develops", "associated"],
    authority: ["misconception", "understand", "explains"],
    city: ["local", "service", "help"],
  };

  const signals = requiredSignals[pageType] ?? [];
  const hits = signals.filter((s) => text.includes(s)).length;

  if (hits === 0) {
    score -= 10;
    reasons.push("Page weakly matches " + pageType + " intent.");
  } else if (hits === 1) {
    score -= 5;
    reasons.push("Page only partially matches " + pageType + " intent.");
  }

  return Math.max(0, score);
}

export function scoreDepth(page: any, pageType: PageType, reasons: string[]): number {
  const c = getContent(page);
  let score = 20;
  const wc = wordCount(c);

  if (pageType === "city") {
    if (wc < 700) {
      score -= 10;
      reasons.push("City page is too thin.");
    }
  } else if (wc < 1100) {
    score -= 12;
    reasons.push("Content is too thin for a gold standard page.");
  }

  if (pageType === "diagnostic") {
    if ((c.top_causes?.length ?? 0) < 4) score -= 3;
    if ((c.repair_matrix?.length ?? 0) < 4) score -= 3;
    if ((c.system_explanation?.length ?? 0) < 4) score -= 2;
  }

  return Math.max(0, score);
}

export function scoreEEAT(page: any, pageType: PageType, reasons: string[]): number {
  const c = getContent(page);
  let score = 15;

  if (!hasExpertObservation(c)) {
    score -= 7;
    reasons.push("Missing strong expert/technical observation.");
  }

  const text = flattenText(c);
  if (!/when to call|when professional help|stop diy|safety/i.test(text)) {
    score -= 3;
    reasons.push("Missing safe escalation or limitation guidance.");
  }

  if (!/why it happens|how it works|failure|pattern|misconception|observable/i.test(text)) {
    score -= 3;
    reasons.push("Weak technical explanation or real-world reasoning.");
  }

  if (pageType === "system") {
    if (!/heat|pressure|phase|airflow/i.test(text)) {
      score -= 5;
      reasons.push("Missing physical/mechanical depth (thermodynamics, phase, pressure, heat, etc.)");
    }

    if (!hasExpertObservation(c)) {
      score -= 5;
      reasons.push("Missing expert insight or tech observation.");
    }

    if (!c.decision_tree && !c.diagram && !c.mermaidGraph) {
      score -= 5;
      reasons.push("Missing Mermaid system diagram");
    }
  }

  return Math.max(0, score);
}

export function scoreReadability(page: any, reasons: string[]): number {
  const c = getContent(page);
  const text = flattenText(c);
  let score = 10;

  if (text.length < 800) {
    score -= 4;
    reasons.push("Readability structure is weak because content is too short.");
  }

  const avgSentenceLength =
    text.split(/[.!?]+/).map((s) => s.trim()).filter(Boolean).reduce((a, s, _, arr) => a + s.split(/\s+/).length / arr.length, 0);

  if (avgSentenceLength > 28) {
    score -= 3;
    reasons.push("Sentences are too long and dense.");
  }

  return Math.max(0, score);
}

export function scoreActionability(page: any, pageType: PageType, reasons: string[]): number {
  const c = getContent(page);
  const text = flattenText(c);
  let score = 10;

  if (!/next step|what to check|what to do|fix|repair|inspect|replace|call/i.test(text)) {
    score -= 5;
    reasons.push("Weak actionability: user cannot easily tell what to do next.");
  }

  if (pageType === "diagnostic" && (!Array.isArray(c.diagnostic_flow) || c.diagnostic_flow.length < 3)) {
    score -= 3;
    reasons.push("Diagnostic page lacks actionable flow.");
  }

  return Math.max(0, score);
}

export function scoreOriginality(page: any, reasons: string[]): number {
  const c = getContent(page);
  const text = flattenText(c);
  let score = 10;

  const patternHits = countPatternMatches(text, HARDCODED_DEFAULT_PATTERNS);
  if (patternHits >= 2) {
    score -= 7;
    reasons.push("Detected hardcoded/generic default language.");
  } else if (patternHits === 1) {
    score -= 3;
    reasons.push("Detected some generic fallback language.");
  }

  const repeatedPhrasePenalty =
    (text.match(/\bimportant to\b/gi)?.length ?? 0) +
    (text.match(/\bcommon issue\b/gi)?.length ?? 0) +
    (text.match(/\bcan be caused by\b/gi)?.length ?? 0);

  if (repeatedPhrasePenalty >= 4) {
    score -= 3;
    reasons.push("Content has repetitive generic phrasing.");
  }

  return Math.max(0, score);
}

export function hasHardRejectConditions(page: any, pageType: PageType): string[] {
  const c = getContent(page);
  const problems: string[] = [];
  const wc = wordCount(c);
  const text = flattenText(c);

  if (!page?.slug) problems.push("Hard reject: missing slug.");
  if (!page?.title) problems.push("Hard reject: missing title.");

  if (pageType === "diagnostic") {
    if (!c.decision_tree) problems.push("Hard reject: missing Mermaid decision_tree.");
    if (!Array.isArray(c.system_explanation) || c.system_explanation.length < 4) {
      problems.push("Hard reject: missing robust system_explanation.");
    }
    if (!Array.isArray(c.diagnostic_flow) || c.diagnostic_flow.length < 3) {
      problems.push("Hard reject: missing diagnostic flow.");
    }
  }

  if (pageType === "system") {
    if (!c.decision_tree && !c.diagram && !c.mermaidGraph) {
      problems.push("Hard reject: missing Mermaid system diagram.");
    }
  }

  if (pageType !== "city" && wc < 700) {
    problems.push("Hard reject: page is far too thin.");
  }

  if (/lorem ipsum|placeholder|tbd|coming soon/i.test(text)) {
    problems.push("Hard reject: placeholder text detected.");
  }

  if (countPatternMatches(text, HARDCODED_DEFAULT_PATTERNS) >= 3) {
    problems.push("Hard reject: heavy fallback/default language detected.");
  }

  return problems;
}

export function scoreGoldStandardPage(
  page: any,
  pageType: PageType
): ValidationResult {
  const reasons: string[] = [];
  const hardRejectReasons = hasHardRejectConditions(page, pageType);

  const sectionScores = {
    schema: scoreSchema(page, pageType, reasons),
    intent: scoreIntent(page, pageType, reasons),
    depth: scoreDepth(page, pageType, reasons),
    eeat: scoreEEAT(page, pageType, reasons),
    readability: scoreReadability(page, reasons),
    actionability: scoreActionability(page, pageType, reasons),
    originality: scoreOriginality(page, reasons),
  };

  const score =
    sectionScores.schema +
    sectionScores.intent +
    sectionScores.depth +
    sectionScores.eeat +
    sectionScores.readability +
    sectionScores.actionability +
    sectionScores.originality;

  const threshold = PUBLISH_THRESHOLDS[pageType] || 85;
  const hardReject = hardRejectReasons.length > 0;
 return {
    valid: !hardReject && sectionScores.schema >= 15 && score >= threshold,
    score,
    retryable: !hardReject && score >= 70,
    reasons: [...hardRejectReasons, ...reasons],
    hardReject,
    sectionScores,
  };
}
